### ISSUE TITLE
Isn't this going to consume too much energy?

### ISSUE THREAD

**Issue by happy-nut** [IMHitesh/HSLocationManager#1]
I cloned your codes and build it. but your app's average energy impact is high.
This 

![image](https://user-images.githubusercontent.com/14966610/67744923-2c65fb80-fa66-11e9-9373-4ab05ab3c134.png)

As you can see, it might be inappropriate for an app to be posted on a real app market. Do you have any ideas to solve this?

**Comment by dung00275** [comment]
@poqw it's result call more times ```startLocationManager()``` , you can remove this and only start only once do not need timer, only keep background task , it's work too.

**Comment by IMHitesh** [comment]
@poqw @dung00275  If you are comment startLocationManager() then it will not be worked if the user locked the device without doing anything. Please keep mind
